name: meditrace
description: "A medication management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  crypto: ^3.0.3

  path_provider: ^2.1.4
  image: ^4.2.0

  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.2.2
  http_parser: ^4.0.2
  flutter_image_compress: ^2.3.0

  google_mlkit_text_recognition: ^0.13.1
  google_mlkit_language_id: ^0.11.1
  google_mlkit_translation: ^0.11.1
  image_picker: ^1.1.1

  # Firebase packages
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_database: ^12.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/try/overrides.json
    - assets/data/test_labels.csv
